---

- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - baseconfig
    - lb-tier

# Setup application servers tier

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - baseconfig
    - app-tier


- name: setup application for app1
  hosts: app1
  become: yes
  gather_facts: false
  roles:
    - application1

- name: setup application for app2
  hosts: app2
  become: yes
  gather_facts: false
  roles:
    - application2


# Setup database tier

- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - baseconfig
    - geerlingguy.postgresql
